moleküle = [
    # Alkane / Cycloalkane
    {"name_de": "Methan", "name_en": "Methane", "smiles": "C", "difficulty": "easy"},
    {"name_de": "Ethan", "name_en": "Ethane", "smiles": "CC", "difficulty": "easy"},
    {"name_de": "Propan", "name_en": "Propane", "smiles": "CCC", "difficulty": "easy"},
    {"name_de": "Butan", "name_en": "Butane", "smiles": "CCCC", "difficulty": "easy"},
    {"name_de": "Isobutan", "name_en": "Isobutane", "smiles": "CC(C)C", "difficulty": "easy"},
    {"name_de": "Pentan", "name_en": "Pentane", "smiles": "CCCCC", "difficulty": "easy"},
    {"name_de": "2-Methylbutan", "name_en": "2-Methylbutane", "smiles": "CC(C)CC", "difficulty": "easy"},
    {"name_de": "Neopentan", "name_en": "Neopentane", "smiles": "CC(C)(C)C", "difficulty": "easy"},
    {"name_de": "1,1-Dimethylpropan", "name_en": "1,1-Dimethylpropane", "smiles": "CC(C)(C)C", "difficulty": "medium"},
    {"name_de": "Hexan", "name_en": "Hexane", "smiles": "CCCCCC", "difficulty": "easy"},
    {"name_de": "2-Methylpentan", "name_en": "2-Methylpentane", "smiles": "CC(C)CCC", "difficulty": "easy"},
    {"name_de": "3-Methylpentan", "name_en": "3-Methylpentane", "smiles": "CCC(C)CC", "difficulty": "easy"},
    {"name_de": "2,2-Dimethylbutan", "name_en": "2,2-Dimethylbutane", "smiles": "CC(C)(C)CC", "difficulty": "medium"},
    {"name_de": "Heptan", "name_en": "Heptane", "smiles": "CCCCCCC", "difficulty": "easy"},
    {"name_de": "Octan", "name_en": "Octane", "smiles": "CCCCCCCC", "difficulty": "easy"},
    {"name_de": "Cyclopropan", "name_en": "Cyclopropane", "smiles": "C1CC1", "difficulty": "easy"},
    {"name_de": "Cyclobutan", "name_en": "Cyclobutane", "smiles": "C1CCC1", "difficulty": "easy"},
    {"name_de": "Cyclopentan", "name_en": "Cyclopentane", "smiles": "C1CCCC1", "difficulty": "easy"},
    {"name_de": "Cyclohexan", "name_en": "Cyclohexane", "smiles": "C1CCCCC1", "difficulty": "easy"},
    {"name_de": "Methylcyclohexan", "name_en": "Methylcyclohexane", "smiles": "CC1CCCCC1", "difficulty": "medium"},
    {"name_de": "Decalin", "name_en": "Decalin", "smiles": "C1CCC2CCCCC2C1", "difficulty": "hard"},

    # Alkene
    {"name_de": "Ethen", "name_en": "Ethene", "smiles": "C=C", "difficulty": "easy"},
    {"name_de": "Propen", "name_en": "Propene", "smiles": "C=CC", "difficulty": "easy"},
    {"name_de": "But-1-en", "name_en": "But-1-ene", "smiles": "C=CCC", "difficulty": "easy"},
    {"name_de": "But-2-en", "name_en": "But-2-ene", "smiles": "CC=CC", "difficulty": "easy"},
    {"name_de": "(E)-But-2-en", "name_en": "(E)-But-2-ene", "smiles": "C/C=C/C", "difficulty": "medium"},
    {"name_de": "(Z)-But-2-en", "name_en": "(Z)-But-2-ene", "smiles": "C/C=C\\C", "difficulty": "medium"},
    {"name_de": "2-Methylpropen", "name_en": "2-Methylpropene", "smiles": "C=C(C)C", "difficulty": "easy"},
    {"name_de": "Pent-1-en", "name_en": "Pent-1-ene", "smiles": "C=CCCC", "difficulty": "easy"},
    {"name_de": "Pent-2-en", "name_en": "Pent-2-ene", "smiles": "CC=CCC", "difficulty": "easy"},
    {"name_de": "(E)-Pent-2-en", "name_en": "(E)-Pent-2-ene", "smiles": "C/C=C/CC", "difficulty": "medium"},
    {"name_de": "(Z)-Pent-2-en", "name_en": "(Z)-Pent-2-ene", "smiles": "C/C=C\\CC", "difficulty": "medium"},
    {"name_de": "2-Methylbut-1-en", "name_en": "2-Methylbut-1-ene", "smiles": "C=C(C)CC", "difficulty": "medium"},
    {"name_de": "2-Methylbut-2-en", "name_en": "2-Methylbut-2-ene", "smiles": "CC=C(C)C", "difficulty": "medium"},
    {"name_de": "Cyclohexen", "name_en": "Cyclohexene", "smiles": "C1=CCCCC1", "difficulty": "medium"},
    {"name_de": "Styrol", "name_en": "Styrene", "smiles": "C=Cc1ccccc1", "difficulty": "medium"},
    {"name_de": "Allylalkohol", "name_en": "Allyl alcohol", "smiles": "C=CCO", "difficulty": "medium"},
    {"name_de": "Acrylsäuremethylester", "name_en": "Methyl acrylate", "smiles": "C=CC(=O)OC", "difficulty": "medium"},
]
